In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from bs4 import BeautifulSoup
import requests
import warnings
warnings.filterwarnings('ignore')

In [4]:
black_labour_force = pd.read_excel('black_labour_force.xlsx')
black_labour_force.head()

,Sigla,Código,Estado,2012 T1,2012 T2,2012 T3,2012 T4,2013 T1,2013 T2,2013 T3,...,2019 T4,2020 T1,2022 T2,2022 T3,2022 T4,2023 T1,2023 T2,2023 T3,2023 T4,2024 T1
0,AC,12,Acre,5.2,3.5,4.0,3.8,3.6,3.5,3.7,...,4.5,4.5,6.9,7.3,7.2,6.5,6.9,6.8,8.7,8.7
1,AL,27,Alagoas,5.8,4.8,3.5,3.4,3.8,3.1,5.4,...,5.6,5.7,7.2,7.4,8.1,8.6,8.3,8.1,8.1,7.5
2,AM,13,Amazonas,3.2,1.9,1.6,1.8,1.7,2.4,3.0,...,2.8,2.3,3.9,4.0,4.3,4.5,4.5,3.9,3.6,3.5
3,AP,16,Amapá,8.7,5.1,4.3,8.0,5.8,7.9,12.8,...,4.5,4.8,7.6,8.6,8.8,9.5,10.6,10.3,9.3,10.3
4,BA,29,Bahia,16.1,16.4,16.0,15.0,15.1,14.3,15.2,...,20.7,20.1,20.5,22.1,22.1,20.4,20.6,20.3,20.8,21.7

In [5]:
black_labour_force.to_csv('black_labour_force_excel.csv')

In [6]:
black_labour_force.columns

Index(['Sigla', 'Código', 'Estado', '2012 T1', '2012 T2', '2012 T3', '2012 T4',
       '2013 T1', '2013 T2', '2013 T3', '2013 T4', '2014 T1', '2014 T2',
       '2014 T3', '2014 T4', '2015 T1', '2015 T2', '2015 T3', '2015 T4',
       '2016 T1', '2016 T2', '2016 T3', '2016 T4', '2017 T1', '2017 T2',
       '2017 T3', '2017 T4', '2018 T1', '2018 T2', '2018 T3', '2018 T4',
       '2019 T1', '2019 T2', '2019 T3', '2019 T4', '2020 T1', '2022 T2',
       '2022 T3', '2022 T4', '2023 T1', '2023 T2', '2023 T3', '2023 T4',
       '2024 T1'],
      dtype='object')

In [7]:
colunas_2012 = ['2012 T1','2012 T2','2012 T3','2012 T4']
colunas_2013 = ['2013 T1','2013 T2','2013 T3','2013 T4']
colunas_2014 = ['2014 T1','2014 T2','2014 T3','2014 T4']
colunas_2015 = ['2015 T1','2015 T2','2015 T3','2015 T4']
colunas_2016 = ['2016 T1','2016 T2','2016 T3','2016 T4']
colunas_2017 = ['2017 T1','2017 T2','2017 T3','2017 T4']
colunas_2018 = ['2018 T1','2018 T2','2018 T3','2018 T4']
colunas_2019 = ['2019 T1','2019 T2','2019 T3','2019 T4']
colunas_2020 = ['2020 T1']
colunas_2022 = ['2022 T2','2022 T3','2022 T4']
colunas_2023 = ['2023 T1','2023 T2','2023 T3','2023 T4']
colunas_2024 = ['2024 T1']

black_labour_force['2012'] = black_labour_force[colunas_2012].mean(axis=1)
black_labour_force['2013'] = black_labour_force[colunas_2013].mean(axis=1)
black_labour_force['2014'] = black_labour_force[colunas_2014].mean(axis=1)
black_labour_force['2015'] = black_labour_force[colunas_2015].mean(axis=1)
black_labour_force['2016'] = black_labour_force[colunas_2016].mean(axis=1)
black_labour_force['2017'] = black_labour_force[colunas_2017].mean(axis=1)
black_labour_force['2018'] = black_labour_force[colunas_2018].mean(axis=1)
black_labour_force['2019'] = black_labour_force[colunas_2019].mean(axis=1)
black_labour_force['2020'] = black_labour_force[colunas_2020].mean(axis=1)
black_labour_force['2022'] = black_labour_force[colunas_2022].mean(axis=1)
black_labour_force['2023'] = black_labour_force[colunas_2023].mean(axis=1)
black_labour_force['2024'] = black_labour_force[colunas_2024].mean(axis=1)

In [8]:
black_labour_force.head()

,Sigla,Código,Estado,2012 T1,2012 T2,2012 T3,2012 T4,2013 T1,2013 T2,2013 T3,...,2014,2015,2016,2017,2018,2019,2020,2022,2023,2024
0,AC,12,Acre,5.2,3.5,4.0,3.8,3.6,3.5,3.7,...,3.625,4.375,4.875,4.650,4.250,4.575,4.5,7.133333,7.225,8.7
1,AL,27,Alagoas,5.8,4.8,3.5,3.4,3.8,3.1,5.4,...,4.575,4.475,5.050,5.175,5.525,5.525,5.7,7.566667,8.275,7.5
2,AM,13,Amazonas,3.2,1.9,1.6,1.8,1.7,2.4,3.0,...,1.950,1.650,1.875,2.350,2.350,3.050,2.3,4.066667,4.125,3.5
3,AP,16,Amapá,8.7,5.1,4.3,8.0,5.8,7.9,12.8,...,11.400,8.950,6.675,6.950,6.500,6.400,4.8,8.333333,9.925,10.3
4,BA,29,Bahia,16.1,16.4,16.0,15.0,15.1,14.3,15.2,...,16.825,17.950,17.700,18.425,19.925,20.350,20.1,21.566667,20.525,21.7

In [9]:
black_labour_force = black_labour_force[['Código', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2022', '2023', '2024']]

In [10]:
black_labour_force.head()

,Código,2012,2013,2014,2015,2016,2017,2018,2019,2020,2022,2023,2024
0,12,4.125,3.725,3.625,4.375,4.875,4.650,4.250,4.575,4.5,7.133333,7.225,8.7
1,27,4.375,4.425,4.575,4.475,5.050,5.175,5.525,5.525,5.7,7.566667,8.275,7.5
2,13,2.125,2.450,1.950,1.650,1.875,2.350,2.350,3.050,2.3,4.066667,4.125,3.5
3,16,6.525,9.475,11.400,8.950,6.675,6.950,6.500,6.400,4.8,8.333333,9.925,10.3
4,29,15.875,14.925,16.825,17.950,17.700,18.425,19.925,20.350,20.1,21.566667,20.525,21.7

In [11]:
black_labour_force_T = black_labour_force.T
print(black_labour_force_T)

               0          1          2          3          4          5   \
Código  12.000000  27.000000  13.000000  16.000000  29.000000  23.000000
2012     4.125000   4.375000   2.125000   6.525000  15.875000   2.975000
2013     3.725000   4.425000   2.450000   9.475000  14.925000   2.725000
2014     3.625000   4.575000   1.950000  11.400000  16.825000   3.125000
2015     4.375000   4.475000   1.650000   8.950000  17.950000   3.575000
2016     4.875000   5.050000   1.875000   6.675000  17.700000   4.225000
2017     4.650000   5.175000   2.350000   6.950000  18.425000   4.175000
2018     4.250000   5.525000   2.350000   6.500000  19.925000   5.000000
2019     4.575000   5.525000   3.050000   6.400000  20.350000   5.175000
2020     4.500000   5.700000   2.300000   4.800000  20.100000   5.600000
2022     7.133333   7.566667   4.066667   8.333333  21.566667   6.766667
2023     7.225000   8.275000   4.125000   9.925000  20.525000   6.350000
2024     8.700000   7.500000   3.500000  10.300000  21.700000   6.200000

               6          7       8          9   ...         17         18  \
Código  53.000000  32.000000  52.000  21.000000  ...  41.000000  33.000000
2012     6.675000   7.425000   6.075   9.425000  ...   3.475000  12.850000
2013     6.875000   8.225000   5.625  11.125000  ...   2.975000  12.550000
2014     7.675000   8.000000   6.150   8.625000  ...   2.825000  11.275000
2015     6.625000   8.825000   5.650   9.025000  ...   3.125000  10.750000
2016     8.250000   8.875000   5.925   9.925000  ...   3.200000  12.025000
2017     8.825000   9.725000   7.050  10.450000  ...   3.500000  12.325000
2018     9.650000  10.850000   8.125  11.800000  ...   3.925000  12.250000
2019    11.275000  10.500000   8.300  12.325000  ...   3.850000  12.375000
2020     9.400000  10.200000   7.100  12.100000  ...   3.700000  13.000000
2022    11.733333  11.466667   9.100  14.933333  ...   4.533333  15.433333
2023    11.175000  11.750000   8.750  14.100000  ...   4.550000  15.350000
2024    11.000000  11.800000   9.200  14.100000  ...   4.500000  15.400000

            19      20         21         22         23         24         25  \
Código  24.000  11.000  14.000000  43.000000  42.000000  28.000000  35.000000
2012     2.775   7.400   5.875000   4.975000   2.325000   7.700000   5.575000
2013     3.000   6.350   5.925000   4.850000   1.875000   6.500000   5.400000
2014     4.075   5.450   6.025000   5.300000   2.250000   5.300000   5.675000
2015     4.625   5.425   7.025000   5.300000   2.100000   6.350000   6.075000
2016     5.425   7.125   7.825000   5.250000   2.225000   6.325000   5.825000
2017     5.600   7.975   9.100000   5.375000   2.475000   6.925000   6.150000
2018     5.975   7.050   7.025000   6.050000   2.700000   7.625000   6.925000
2019     8.075   6.900   8.775000   6.200000   2.900000   8.975000   6.875000
2020     7.700   8.200   7.500000   5.700000   2.600000   9.500000   6.900000
2022     8.700   8.000   7.933333   5.866667   3.433333  11.366667   7.433333
2023     9.075   7.300   8.700000   6.675000   3.750000  11.375000   7.575000
2024     9.800   7.300   9.300000   7.100000   3.300000  12.000000   7.600000

               26
Código  17.000000
2012     7.150000
2013     7.325000
2014     8.025000
2015     9.650000
2016    11.550000
2017    11.625000
2018    12.375000
2019    12.075000
2020    12.900000
2022    13.633333
2023    14.825000
2024    15.500000

[13 rows x 27 columns]

In [12]:
black_labour_force_T = black_labour_force_T.reset_index()
print(black_labour_force_T)

     index          0          1          2          3          4          5  \
0   Código  12.000000  27.000000  13.000000  16.000000  29.000000  23.000000
1     2012   4.125000   4.375000   2.125000   6.525000  15.875000   2.975000
2     2013   3.725000   4.425000   2.450000   9.475000  14.925000   2.725000
3     2014   3.625000   4.575000   1.950000  11.400000  16.825000   3.125000
4     2015   4.375000   4.475000   1.650000   8.950000  17.950000   3.575000
5     2016   4.875000   5.050000   1.875000   6.675000  17.700000   4.225000
6     2017   4.650000   5.175000   2.350000   6.950000  18.425000   4.175000
7     2018   4.250000   5.525000   2.350000   6.500000  19.925000   5.000000
8     2019   4.575000   5.525000   3.050000   6.400000  20.350000   5.175000
9     2020   4.500000   5.700000   2.300000   4.800000  20.100000   5.600000
10    2022   7.133333   7.566667   4.066667   8.333333  21.566667   6.766667
11    2023   7.225000   8.275000   4.125000   9.925000  20.525000   6.350000
12    2024   8.700000   7.500000   3.500000  10.300000  21.700000   6.200000

            6          7       8  ...         17         18      19      20  \
0   53.000000  32.000000  52.000  ...  41.000000  33.000000  24.000  11.000
1    6.675000   7.425000   6.075  ...   3.475000  12.850000   2.775   7.400
2    6.875000   8.225000   5.625  ...   2.975000  12.550000   3.000   6.350
3    7.675000   8.000000   6.150  ...   2.825000  11.275000   4.075   5.450
4    6.625000   8.825000   5.650  ...   3.125000  10.750000   4.625   5.425
5    8.250000   8.875000   5.925  ...   3.200000  12.025000   5.425   7.125
6    8.825000   9.725000   7.050  ...   3.500000  12.325000   5.600   7.975
7    9.650000  10.850000   8.125  ...   3.925000  12.250000   5.975   7.050
8   11.275000  10.500000   8.300  ...   3.850000  12.375000   8.075   6.900
9    9.400000  10.200000   7.100  ...   3.700000  13.000000   7.700   8.200
10  11.733333  11.466667   9.100  ...   4.533333  15.433333   8.700   8.000
11  11.175000  11.750000   8.750  ...   4.550000  15.350000   9.075   7.300
12  11.000000  11.800000   9.200  ...   4.500000  15.400000   9.800   7.300

           21         22         23         24         25         26
0   14.000000  43.000000  42.000000  28.000000  35.000000  17.000000
1    5.875000   4.975000   2.325000   7.700000   5.575000   7.150000
2    5.925000   4.850000   1.875000   6.500000   5.400000   7.325000
3    6.025000   5.300000   2.250000   5.300000   5.675000   8.025000
4    7.025000   5.300000   2.100000   6.350000   6.075000   9.650000
5    7.825000   5.250000   2.225000   6.325000   5.825000  11.550000
6    9.100000   5.375000   2.475000   6.925000   6.150000  11.625000
7    7.025000   6.050000   2.700000   7.625000   6.925000  12.375000
8    8.775000   6.200000   2.900000   8.975000   6.875000  12.075000
9    7.500000   5.700000   2.600000   9.500000   6.900000  12.900000
10   7.933333   5.866667   3.433333  11.366667   7.433333  13.633333
11   8.700000   6.675000   3.750000  11.375000   7.575000  14.825000
12   9.300000   7.100000   3.300000  12.000000   7.600000  15.500000

[13 rows x 28 columns]

In [13]:
new_columns_names = black_labour_force_T.iloc[0].tolist()
new_columns_names= dict(zip(black_labour_force_T.columns, new_columns_names))
black_labour_force_T.rename(columns = new_columns_names, inplace=True)
print(black_labour_force_T)

    Código       12.0       27.0       13.0       16.0       29.0       23.0  \
0   Código  12.000000  27.000000  13.000000  16.000000  29.000000  23.000000
1     2012   4.125000   4.375000   2.125000   6.525000  15.875000   2.975000
2     2013   3.725000   4.425000   2.450000   9.475000  14.925000   2.725000
3     2014   3.625000   4.575000   1.950000  11.400000  16.825000   3.125000
4     2015   4.375000   4.475000   1.650000   8.950000  17.950000   3.575000
5     2016   4.875000   5.050000   1.875000   6.675000  17.700000   4.225000
6     2017   4.650000   5.175000   2.350000   6.950000  18.425000   4.175000
7     2018   4.250000   5.525000   2.350000   6.500000  19.925000   5.000000
8     2019   4.575000   5.525000   3.050000   6.400000  20.350000   5.175000
9     2020   4.500000   5.700000   2.300000   4.800000  20.100000   5.600000
10    2022   7.133333   7.566667   4.066667   8.333333  21.566667   6.766667
11    2023   7.225000   8.275000   4.125000   9.925000  20.525000   6.350000
12    2024   8.700000   7.500000   3.500000  10.300000  21.700000   6.200000

         53.0       32.0    52.0  ...       41.0       33.0    24.0    11.0  \
0   53.000000  32.000000  52.000  ...  41.000000  33.000000  24.000  11.000
1    6.675000   7.425000   6.075  ...   3.475000  12.850000   2.775   7.400
2    6.875000   8.225000   5.625  ...   2.975000  12.550000   3.000   6.350
3    7.675000   8.000000   6.150  ...   2.825000  11.275000   4.075   5.450
4    6.625000   8.825000   5.650  ...   3.125000  10.750000   4.625   5.425
5    8.250000   8.875000   5.925  ...   3.200000  12.025000   5.425   7.125
6    8.825000   9.725000   7.050  ...   3.500000  12.325000   5.600   7.975
7    9.650000  10.850000   8.125  ...   3.925000  12.250000   5.975   7.050
8   11.275000  10.500000   8.300  ...   3.850000  12.375000   8.075   6.900
9    9.400000  10.200000   7.100  ...   3.700000  13.000000   7.700   8.200
10  11.733333  11.466667   9.100  ...   4.533333  15.433333   8.700   8.000
11  11.175000  11.750000   8.750  ...   4.550000  15.350000   9.075   7.300
12  11.000000  11.800000   9.200  ...   4.500000  15.400000   9.800   7.300

         14.0       43.0       42.0       28.0       35.0       17.0
0   14.000000  43.000000  42.000000  28.000000  35.000000  17.000000
1    5.875000   4.975000   2.325000   7.700000   5.575000   7.150000
2    5.925000   4.850000   1.875000   6.500000   5.400000   7.325000
3    6.025000   5.300000   2.250000   5.300000   5.675000   8.025000
4    7.025000   5.300000   2.100000   6.350000   6.075000   9.650000
5    7.825000   5.250000   2.225000   6.325000   5.825000  11.550000
6    9.100000   5.375000   2.475000   6.925000   6.150000  11.625000
7    7.025000   6.050000   2.700000   7.625000   6.925000  12.375000
8    8.775000   6.200000   2.900000   8.975000   6.875000  12.075000
9    7.500000   5.700000   2.600000   9.500000   6.900000  12.900000
10   7.933333   5.866667   3.433333  11.366667   7.433333  13.633333
11   8.700000   6.675000   3.750000  11.375000   7.575000  14.825000
12   9.300000   7.100000   3.300000  12.000000   7.600000  15.500000

[13 rows x 28 columns]

In [14]:
black_labour_force_T = black_labour_force_T.drop(index=0)
print(black_labour_force_T)

   Código      12.0      27.0      13.0       16.0       29.0      23.0  \
1    2012  4.125000  4.375000  2.125000   6.525000  15.875000  2.975000
2    2013  3.725000  4.425000  2.450000   9.475000  14.925000  2.725000
3    2014  3.625000  4.575000  1.950000  11.400000  16.825000  3.125000
4    2015  4.375000  4.475000  1.650000   8.950000  17.950000  3.575000
5    2016  4.875000  5.050000  1.875000   6.675000  17.700000  4.225000
6    2017  4.650000  5.175000  2.350000   6.950000  18.425000  4.175000
7    2018  4.250000  5.525000  2.350000   6.500000  19.925000  5.000000
8    2019  4.575000  5.525000  3.050000   6.400000  20.350000  5.175000
9    2020  4.500000  5.700000  2.300000   4.800000  20.100000  5.600000
10   2022  7.133333  7.566667  4.066667   8.333333  21.566667  6.766667
11   2023  7.225000  8.275000  4.125000   9.925000  20.525000  6.350000
12   2024  8.700000  7.500000  3.500000  10.300000  21.700000  6.200000

         53.0       32.0   52.0  ...      41.0       33.0   24.0   11.0  \
1    6.675000   7.425000  6.075  ...  3.475000  12.850000  2.775  7.400
2    6.875000   8.225000  5.625  ...  2.975000  12.550000  3.000  6.350
3    7.675000   8.000000  6.150  ...  2.825000  11.275000  4.075  5.450
4    6.625000   8.825000  5.650  ...  3.125000  10.750000  4.625  5.425
5    8.250000   8.875000  5.925  ...  3.200000  12.025000  5.425  7.125
6    8.825000   9.725000  7.050  ...  3.500000  12.325000  5.600  7.975
7    9.650000  10.850000  8.125  ...  3.925000  12.250000  5.975  7.050
8   11.275000  10.500000  8.300  ...  3.850000  12.375000  8.075  6.900
9    9.400000  10.200000  7.100  ...  3.700000  13.000000  7.700  8.200
10  11.733333  11.466667  9.100  ...  4.533333  15.433333  8.700  8.000
11  11.175000  11.750000  8.750  ...  4.550000  15.350000  9.075  7.300
12  11.000000  11.800000  9.200  ...  4.500000  15.400000  9.800  7.300

        14.0      43.0      42.0       28.0      35.0       17.0
1   5.875000  4.975000  2.325000   7.700000  5.575000   7.150000
2   5.925000  4.850000  1.875000   6.500000  5.400000   7.325000
3   6.025000  5.300000  2.250000   5.300000  5.675000   8.025000
4   7.025000  5.300000  2.100000   6.350000  6.075000   9.650000
5   7.825000  5.250000  2.225000   6.325000  5.825000  11.550000
6   9.100000  5.375000  2.475000   6.925000  6.150000  11.625000
7   7.025000  6.050000  2.700000   7.625000  6.925000  12.375000
8   8.775000  6.200000  2.900000   8.975000  6.875000  12.075000
9   7.500000  5.700000  2.600000   9.500000  6.900000  12.900000
10  7.933333  5.866667  3.433333  11.366667  7.433333  13.633333
11  8.700000  6.675000  3.750000  11.375000  7.575000  14.825000
12  9.300000  7.100000  3.300000  12.000000  7.600000  15.500000

[12 rows x 28 columns]

In [15]:
black_labour_force_T.rename(columns = {'Código' : 'time'}, inplace = True)
print(black_labour_force_T)

    time      12.0      27.0      13.0       16.0       29.0      23.0  \
1   2012  4.125000  4.375000  2.125000   6.525000  15.875000  2.975000
2   2013  3.725000  4.425000  2.450000   9.475000  14.925000  2.725000
3   2014  3.625000  4.575000  1.950000  11.400000  16.825000  3.125000
4   2015  4.375000  4.475000  1.650000   8.950000  17.950000  3.575000
5   2016  4.875000  5.050000  1.875000   6.675000  17.700000  4.225000
6   2017  4.650000  5.175000  2.350000   6.950000  18.425000  4.175000
7   2018  4.250000  5.525000  2.350000   6.500000  19.925000  5.000000
8   2019  4.575000  5.525000  3.050000   6.400000  20.350000  5.175000
9   2020  4.500000  5.700000  2.300000   4.800000  20.100000  5.600000
10  2022  7.133333  7.566667  4.066667   8.333333  21.566667  6.766667
11  2023  7.225000  8.275000  4.125000   9.925000  20.525000  6.350000
12  2024  8.700000  7.500000  3.500000  10.300000  21.700000  6.200000

         53.0       32.0   52.0  ...      41.0       33.0   24.0   11.0  \
1    6.675000   7.425000  6.075  ...  3.475000  12.850000  2.775  7.400
2    6.875000   8.225000  5.625  ...  2.975000  12.550000  3.000  6.350
3    7.675000   8.000000  6.150  ...  2.825000  11.275000  4.075  5.450
4    6.625000   8.825000  5.650  ...  3.125000  10.750000  4.625  5.425
5    8.250000   8.875000  5.925  ...  3.200000  12.025000  5.425  7.125
6    8.825000   9.725000  7.050  ...  3.500000  12.325000  5.600  7.975
7    9.650000  10.850000  8.125  ...  3.925000  12.250000  5.975  7.050
8   11.275000  10.500000  8.300  ...  3.850000  12.375000  8.075  6.900
9    9.400000  10.200000  7.100  ...  3.700000  13.000000  7.700  8.200
10  11.733333  11.466667  9.100  ...  4.533333  15.433333  8.700  8.000
11  11.175000  11.750000  8.750  ...  4.550000  15.350000  9.075  7.300
12  11.000000  11.800000  9.200  ...  4.500000  15.400000  9.800  7.300

        14.0      43.0      42.0       28.0      35.0       17.0
1   5.875000  4.975000  2.325000   7.700000  5.575000   7.150000
2   5.925000  4.850000  1.875000   6.500000  5.400000   7.325000
3   6.025000  5.300000  2.250000   5.300000  5.675000   8.025000
4   7.025000  5.300000  2.100000   6.350000  6.075000   9.650000
5   7.825000  5.250000  2.225000   6.325000  5.825000  11.550000
6   9.100000  5.375000  2.475000   6.925000  6.150000  11.625000
7   7.025000  6.050000  2.700000   7.625000  6.925000  12.375000
8   8.775000  6.200000  2.900000   8.975000  6.875000  12.075000
9   7.500000  5.700000  2.600000   9.500000  6.900000  12.900000
10  7.933333  5.866667  3.433333  11.366667  7.433333  13.633333
11  8.700000  6.675000  3.750000  11.375000  7.575000  14.825000
12  9.300000  7.100000  3.300000  12.000000  7.600000  15.500000

[12 rows x 28 columns]

In [16]:
black_labour_force_T.rename(columns = {12.0 : '12', 27.0 : '27', 13.0 : '13', 16.0 : '16', 29.0 : '29', 23.0 : '23', 53.0 : '53', 32.0 : '32', 52.0 : '52', 21.0 : '21', 31.0 : '31', 50.0 : '50', 51.0 : '51', 15.0 : '15', 25.0 : '25', 26.0 : '26', 22.0 : '22', 41.0 : '41', 33.0 : '33', 24.0 : '24', 11.0 : '11', 14.0 : '14', 43.0 : '43', 42.0 : '42', 28.0 : '28', 35.0 : '35', 17.0 : '17'}, inplace = True)
print(black_labour_force_T)

    time        12        27        13         16         29        23  \
1   2012  4.125000  4.375000  2.125000   6.525000  15.875000  2.975000
2   2013  3.725000  4.425000  2.450000   9.475000  14.925000  2.725000
3   2014  3.625000  4.575000  1.950000  11.400000  16.825000  3.125000
4   2015  4.375000  4.475000  1.650000   8.950000  17.950000  3.575000
5   2016  4.875000  5.050000  1.875000   6.675000  17.700000  4.225000
6   2017  4.650000  5.175000  2.350000   6.950000  18.425000  4.175000
7   2018  4.250000  5.525000  2.350000   6.500000  19.925000  5.000000
8   2019  4.575000  5.525000  3.050000   6.400000  20.350000  5.175000
9   2020  4.500000  5.700000  2.300000   4.800000  20.100000  5.600000
10  2022  7.133333  7.566667  4.066667   8.333333  21.566667  6.766667
11  2023  7.225000  8.275000  4.125000   9.925000  20.525000  6.350000
12  2024  8.700000  7.500000  3.500000  10.300000  21.700000  6.200000

           53         32     52  ...        41         33     24     11  \
1    6.675000   7.425000  6.075  ...  3.475000  12.850000  2.775  7.400
2    6.875000   8.225000  5.625  ...  2.975000  12.550000  3.000  6.350
3    7.675000   8.000000  6.150  ...  2.825000  11.275000  4.075  5.450
4    6.625000   8.825000  5.650  ...  3.125000  10.750000  4.625  5.425
5    8.250000   8.875000  5.925  ...  3.200000  12.025000  5.425  7.125
6    8.825000   9.725000  7.050  ...  3.500000  12.325000  5.600  7.975
7    9.650000  10.850000  8.125  ...  3.925000  12.250000  5.975  7.050
8   11.275000  10.500000  8.300  ...  3.850000  12.375000  8.075  6.900
9    9.400000  10.200000  7.100  ...  3.700000  13.000000  7.700  8.200
10  11.733333  11.466667  9.100  ...  4.533333  15.433333  8.700  8.000
11  11.175000  11.750000  8.750  ...  4.550000  15.350000  9.075  7.300
12  11.000000  11.800000  9.200  ...  4.500000  15.400000  9.800  7.300

          14        43        42         28        35         17
1   5.875000  4.975000  2.325000   7.700000  5.575000   7.150000
2   5.925000  4.850000  1.875000   6.500000  5.400000   7.325000
3   6.025000  5.300000  2.250000   5.300000  5.675000   8.025000
4   7.025000  5.300000  2.100000   6.350000  6.075000   9.650000
5   7.825000  5.250000  2.225000   6.325000  5.825000  11.550000
6   9.100000  5.375000  2.475000   6.925000  6.150000  11.625000
7   7.025000  6.050000  2.700000   7.625000  6.925000  12.375000
8   8.775000  6.200000  2.900000   8.975000  6.875000  12.075000
9   7.500000  5.700000  2.600000   9.500000  6.900000  12.900000
10  7.933333  5.866667  3.433333  11.366667  7.433333  13.633333
11  8.700000  6.675000  3.750000  11.375000  7.575000  14.825000
12  9.300000  7.100000  3.300000  12.000000  7.600000  15.500000

[12 rows x 28 columns]

In [17]:
black_labour_force_T.columns

Index(['time', '12', '27', '13', '16', '29', '23', '53', '32', '52', '21',
       '31', '50', '51', '15', '25', '26', '22', '41', '33', '24', '11', '14',
       '43', '42', '28', '35', '17'],
      dtype='object')

In [18]:
colunas_arredondar = ['12', '27', '13', '16', '29', '23', '53', '32', '52', '21',
       '31', '50', '51', '15', '25', '26', '22', '41', '33', '24', '11', '14',
       '43', '42', '28', '35', '17']
black_labour_force_T[colunas_arredondar] = black_labour_force_T[colunas_arredondar].round(1)

In [19]:
print(black_labour_force_T)

    time   12   27   13    16    29   23    53    32   52  ...   41    33  \
1   2012  4.1  4.4  2.1   6.5  15.9  3.0   6.7   7.4  6.1  ...  3.5  12.8
2   2013  3.7  4.4  2.4   9.5  14.9  2.7   6.9   8.2  5.6  ...  3.0  12.6
3   2014  3.6  4.6  2.0  11.4  16.8  3.1   7.7   8.0  6.2  ...  2.8  11.3
4   2015  4.4  4.5  1.6   9.0  18.0  3.6   6.6   8.8  5.6  ...  3.1  10.8
5   2016  4.9  5.0  1.9   6.7  17.7  4.2   8.2   8.9  5.9  ...  3.2  12.0
6   2017  4.6  5.2  2.4   7.0  18.4  4.2   8.8   9.7  7.0  ...  3.5  12.3
7   2018  4.2  5.5  2.4   6.5  19.9  5.0   9.6  10.8  8.1  ...  3.9  12.2
8   2019  4.6  5.5  3.0   6.4  20.4  5.2  11.3  10.5  8.3  ...  3.9  12.4
9   2020  4.5  5.7  2.3   4.8  20.1  5.6   9.4  10.2  7.1  ...  3.7  13.0
10  2022  7.1  7.6  4.1   8.3  21.6  6.8  11.7  11.5  9.1  ...  4.5  15.4
11  2023  7.2  8.3  4.1   9.9  20.5  6.4  11.2  11.8  8.8  ...  4.6  15.4
12  2024  8.7  7.5  3.5  10.3  21.7  6.2  11.0  11.8  9.2  ...  4.5  15.4

     24   11   14   43   42    28   35    17
1   2.8  7.4  5.9  5.0  2.3   7.7  5.6   7.2
2   3.0  6.4  5.9  4.8  1.9   6.5  5.4   7.3
3   4.1  5.4  6.0  5.3  2.2   5.3  5.7   8.0
4   4.6  5.4  7.0  5.3  2.1   6.4  6.1   9.6
5   5.4  7.1  7.8  5.2  2.2   6.3  5.8  11.5
6   5.6  8.0  9.1  5.4  2.5   6.9  6.1  11.6
7   6.0  7.0  7.0  6.1  2.7   7.6  6.9  12.4
8   8.1  6.9  8.8  6.2  2.9   9.0  6.9  12.1
9   7.7  8.2  7.5  5.7  2.6   9.5  6.9  12.9
10  8.7  8.0  7.9  5.9  3.4  11.4  7.4  13.6
11  9.1  7.3  8.7  6.7  3.7  11.4  7.6  14.8
12  9.8  7.3  9.3  7.1  3.3  12.0  7.6  15.5

[12 rows x 28 columns]

In [20]:
black_labour_force = black_labour_force_T
black_labour_force.to_csv('black_labour_force_est.csv')