In [219]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from bs4 import BeautifulSoup
import requests
import warnings
warnings.filterwarnings('ignore')

In [220]:
#Carregando nosso DF
os.chdir('/content/drive/MyDrive/Bases de Dados para Indicadores EUROFOUND/Base de Dados')
international_poverty_states_br = pd.read_csv('taxa_pobreza_internacional.csv', sep =';')

In [221]:
international_poverty_states_br.head()

,Sigla,C칩digo,Estado,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,AC,12,Acre,"14,3","13,1","11,1","11,7","15,9","16,8","16,3","17,8","10,4","17,6",14
1,AL,27,Alagoas,"13,1","14,2","13,8","14,3","15,2","16,9","19,3","16,5","12,2","16,4","13,1"
2,AM,13,Amazonas,"12,6","11,2","10,1","11,7","14,6","15,1","15,5","16,8","13,2","16,2","10,5"
3,AP,16,Amap치,"8,2","5,6","7,1","11,5","11,1",10,"10,7","7,9","10,5","11,8","7,9"
4,BA,29,Bahia,"14,5",12,9,11,"12,9","15,6","15,3","14,5","10,3",17,"11,9"

In [222]:
#Selecionando apenas as colunas que vamos precisar
international_poverty_states_br = international_poverty_states_br.drop(['Sigla', 'Estado'], axis = 1)

In [223]:
international_poverty_states_br.head()

   C칩digo  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  2022
0      12  14,3  13,1  11,1  11,7  15,9  16,8  16,3  17,8  10,4  17,6    14
1      27  13,1  14,2  13,8  14,3  15,2  16,9  19,3  16,5  12,2  16,4  13,1
2      13  12,6  11,2  10,1  11,7  14,6  15,1  15,5  16,8  13,2  16,2  10,5
3      16   8,2   5,6   7,1  11,5  11,1    10  10,7   7,9  10,5  11,8   7,9
4      29  14,5    12     9    11  12,9  15,6  15,3  14,5  10,3    17  11,9

In [224]:
#Transpondo nosso DF
international_poverty_states_br_T = international_poverty_states_br.T
international_poverty_states_br_T = international_poverty_states_br_T.set_index(international_poverty_states_br.columns)

In [225]:
print(international_poverty_states_br_T)

          0     1     2     3     4     5    6    7    8     9   ...   17  \
C칩digo    12    27    13    16    29    23   53   32   52    21  ...   41
2012    14,3  13,1  12,6   8,2  14,5  14,5  2,1  3,2  2,1  19,9  ...  2,3
2013    13,1  14,2  11,2   5,6    12  13,8  2,8  3,7  1,8  18,4  ...  1,7
2014    11,1  13,8  10,1   7,1     9  11,9    2  3,6  2,3  16,7  ...  1,8
2015    11,7  14,3  11,7  11,5    11  12,1  2,4  4,6  2,1  17,4  ...  2,2
2016    15,9  15,2  14,6  11,1  12,9  14,1  1,9    5  3,7  19,4  ...  2,3
2017    16,8  16,9  15,1    10  15,6  13,9  3,7  5,6  3,2  20,4  ...    3
2018    16,3  19,3  15,5  10,7  15,3  13,6  3,3  4,5  3,4  21,8  ...  3,1
2019    17,8  16,5  16,8   7,9  14,5  13,5  1,8  3,9  3,7  22,5  ...  2,8
2020    10,4  12,2  13,2  10,5  10,3   9,9  2,9  4,4  3,3  15,1  ...  3,9
2021    17,6  16,4  16,2  11,8    17    16  4,3  7,2  3,8  22,6  ...  3,9
2022      14  13,1  10,5   7,9  11,9  10,9  1,8  4,1  2,7    15  ...  2,9

         18    19   20    21   22   23    24   25   26
C칩digo   33    24   11    14   43   42    28   35   17
2012    3,5  10,3  6,1   6,5  2,2  1,5  11,9  2,2  6,5
2013    3,3   8,7    6   5,6  1,7  1,1   9,9    2  7,4
2014    2,9   8,5  4,7   5,5  1,8  0,9   8,9  1,9  5,8
2015      3   8,3  4,7   4,5  1,6  1,1     9    2  6,6
2016    3,6   9,8  5,9   6,1  2,2  1,8  12,3  2,6  7,5
2017    4,1    12  5,3   7,9  2,7  1,6    15    3  5,8
2018    4,2  11,6  5,3   9,4  2,4  1,6  15,4  3,1    8
2019    4,5    12  5,2  12,5  2,5  1,7    14  2,7  8,9
2020    5,8   6,3  5,2  10,4  2,5    2   8,4  3,3  5,9
2021    7,6  14,9  8,1  11,3  2,9  2,4  14,9  4,4  7,6
2022    4,5   9,4  4,3   7,8  2,5  1,8   8,9  2,9  4,9

[12 rows x 27 columns]

In [226]:
#Criando o index superior
international_poverty_states_br_T = international_poverty_states_br_T.reset_index(drop=False)

In [227]:
print(international_poverty_states_br_T)

     index     0     1     2     3     4     5    6    7    8  ...   17   18  \
0   C칩digo    12    27    13    16    29    23   53   32   52  ...   41   33
1     2012  14,3  13,1  12,6   8,2  14,5  14,5  2,1  3,2  2,1  ...  2,3  3,5
2     2013  13,1  14,2  11,2   5,6    12  13,8  2,8  3,7  1,8  ...  1,7  3,3
3     2014  11,1  13,8  10,1   7,1     9  11,9    2  3,6  2,3  ...  1,8  2,9
4     2015  11,7  14,3  11,7  11,5    11  12,1  2,4  4,6  2,1  ...  2,2    3
5     2016  15,9  15,2  14,6  11,1  12,9  14,1  1,9    5  3,7  ...  2,3  3,6
6     2017  16,8  16,9  15,1    10  15,6  13,9  3,7  5,6  3,2  ...    3  4,1
7     2018  16,3  19,3  15,5  10,7  15,3  13,6  3,3  4,5  3,4  ...  3,1  4,2
8     2019  17,8  16,5  16,8   7,9  14,5  13,5  1,8  3,9  3,7  ...  2,8  4,5
9     2020  10,4  12,2  13,2  10,5  10,3   9,9  2,9  4,4  3,3  ...  3,9  5,8
10    2021  17,6  16,4  16,2  11,8    17    16  4,3  7,2  3,8  ...  3,9  7,6
11    2022    14  13,1  10,5   7,9  11,9  10,9  1,8  4,1  2,7  ...  2,9  4,5

      19   20    21   22   23    24   25   26
0     24   11    14   43   42    28   35   17
1   10,3  6,1   6,5  2,2  1,5  11,9  2,2  6,5
2    8,7    6   5,6  1,7  1,1   9,9    2  7,4
3    8,5  4,7   5,5  1,8  0,9   8,9  1,9  5,8
4    8,3  4,7   4,5  1,6  1,1     9    2  6,6
5    9,8  5,9   6,1  2,2  1,8  12,3  2,6  7,5
6     12  5,3   7,9  2,7  1,6    15    3  5,8
7   11,6  5,3   9,4  2,4  1,6  15,4  3,1    8
8     12  5,2  12,5  2,5  1,7    14  2,7  8,9
9    6,3  5,2  10,4  2,5    2   8,4  3,3  5,9
10  14,9  8,1  11,3  2,9  2,4  14,9  4,4  7,6
11   9,4  4,3   7,8  2,5  1,8   8,9  2,9  4,9

[12 rows x 28 columns]

In [228]:
print(international_poverty_states_br_T.iloc[0])

index    C칩digo
0            12
1            27
2            13
3            16
4            29
5            23
6            53
7            32
8            52
9            21
10           31
11           50
12           51
13           15
14           25
15           26
16           22
17           41
18           33
19           24
20           11
21           14
22           43
23           42
24           28
25           35
26           17
Name: 0, dtype: object

In [229]:
#Removendo o index superior e renomeando as colunas
new_columns_names = international_poverty_states_br_T.iloc[0].tolist()

In [230]:
new_columns_names = dict(zip(international_poverty_states_br_T.columns, new_columns_names))
international_poverty_states_br_T.rename(columns = new_columns_names, inplace=True)

In [231]:
print(international_poverty_states_br_T)

    C칩digo    12    27    13    16    29    23   53   32   52  ...   41   33  \
0   C칩digo    12    27    13    16    29    23   53   32   52  ...   41   33
1     2012  14,3  13,1  12,6   8,2  14,5  14,5  2,1  3,2  2,1  ...  2,3  3,5
2     2013  13,1  14,2  11,2   5,6    12  13,8  2,8  3,7  1,8  ...  1,7  3,3
3     2014  11,1  13,8  10,1   7,1     9  11,9    2  3,6  2,3  ...  1,8  2,9
4     2015  11,7  14,3  11,7  11,5    11  12,1  2,4  4,6  2,1  ...  2,2    3
5     2016  15,9  15,2  14,6  11,1  12,9  14,1  1,9    5  3,7  ...  2,3  3,6
6     2017  16,8  16,9  15,1    10  15,6  13,9  3,7  5,6  3,2  ...    3  4,1
7     2018  16,3  19,3  15,5  10,7  15,3  13,6  3,3  4,5  3,4  ...  3,1  4,2
8     2019  17,8  16,5  16,8   7,9  14,5  13,5  1,8  3,9  3,7  ...  2,8  4,5
9     2020  10,4  12,2  13,2  10,5  10,3   9,9  2,9  4,4  3,3  ...  3,9  5,8
10    2021  17,6  16,4  16,2  11,8    17    16  4,3  7,2  3,8  ...  3,9  7,6
11    2022    14  13,1  10,5   7,9  11,9  10,9  1,8  4,1  2,7  ...  2,9  4,5

      24   11    14   43   42    28   35   17
0     24   11    14   43   42    28   35   17
1   10,3  6,1   6,5  2,2  1,5  11,9  2,2  6,5
2    8,7    6   5,6  1,7  1,1   9,9    2  7,4
3    8,5  4,7   5,5  1,8  0,9   8,9  1,9  5,8
4    8,3  4,7   4,5  1,6  1,1     9    2  6,6
5    9,8  5,9   6,1  2,2  1,8  12,3  2,6  7,5
6     12  5,3   7,9  2,7  1,6    15    3  5,8
7   11,6  5,3   9,4  2,4  1,6  15,4  3,1    8
8     12  5,2  12,5  2,5  1,7    14  2,7  8,9
9    6,3  5,2  10,4  2,5    2   8,4  3,3  5,9
10  14,9  8,1  11,3  2,9  2,4  14,9  4,4  7,6
11   9,4  4,3   7,8  2,5  1,8   8,9  2,9  4,9

[12 rows x 28 columns]

In [232]:
#Removendo a primeira linha repetida
international_poverty_states_br_T = international_poverty_states_br_T.drop(index=0)
print(international_poverty_states_br_T)

   C칩digo    12    27    13    16    29    23   53   32   52  ...   41   33  \
1    2012  14,3  13,1  12,6   8,2  14,5  14,5  2,1  3,2  2,1  ...  2,3  3,5
2    2013  13,1  14,2  11,2   5,6    12  13,8  2,8  3,7  1,8  ...  1,7  3,3
3    2014  11,1  13,8  10,1   7,1     9  11,9    2  3,6  2,3  ...  1,8  2,9
4    2015  11,7  14,3  11,7  11,5    11  12,1  2,4  4,6  2,1  ...  2,2    3
5    2016  15,9  15,2  14,6  11,1  12,9  14,1  1,9    5  3,7  ...  2,3  3,6
6    2017  16,8  16,9  15,1    10  15,6  13,9  3,7  5,6  3,2  ...    3  4,1
7    2018  16,3  19,3  15,5  10,7  15,3  13,6  3,3  4,5  3,4  ...  3,1  4,2
8    2019  17,8  16,5  16,8   7,9  14,5  13,5  1,8  3,9  3,7  ...  2,8  4,5
9    2020  10,4  12,2  13,2  10,5  10,3   9,9  2,9  4,4  3,3  ...  3,9  5,8
10   2021  17,6  16,4  16,2  11,8    17    16  4,3  7,2  3,8  ...  3,9  7,6
11   2022    14  13,1  10,5   7,9  11,9  10,9  1,8  4,1  2,7  ...  2,9  4,5

      24   11    14   43   42    28   35   17
1   10,3  6,1   6,5  2,2  1,5  11,9  2,2  6,5
2    8,7    6   5,6  1,7  1,1   9,9    2  7,4
3    8,5  4,7   5,5  1,8  0,9   8,9  1,9  5,8
4    8,3  4,7   4,5  1,6  1,1     9    2  6,6
5    9,8  5,9   6,1  2,2  1,8  12,3  2,6  7,5
6     12  5,3   7,9  2,7  1,6    15    3  5,8
7   11,6  5,3   9,4  2,4  1,6  15,4  3,1    8
8     12  5,2  12,5  2,5  1,7    14  2,7  8,9
9    6,3  5,2  10,4  2,5    2   8,4  3,3  5,9
10  14,9  8,1  11,3  2,9  2,4  14,9  4,4  7,6
11   9,4  4,3   7,8  2,5  1,8   8,9  2,9  4,9

[11 rows x 28 columns]

In [233]:
international_poverty_states_br_T.head()

,C칩digo,12,27,13,16,29,23,53,32,52,...,41,33,24,11,14,43,42,28,35,17
1,2012,"14,3","13,1","12,6","8,2","14,5","14,5","2,1","3,2","2,1",...,"2,3","3,5","10,3","6,1","6,5","2,2","1,5","11,9","2,2","6,5"
2,2013,"13,1","14,2","11,2","5,6",12,"13,8","2,8","3,7","1,8",...,"1,7","3,3","8,7",6,"5,6","1,7","1,1","9,9",2,"7,4"
3,2014,"11,1","13,8","10,1","7,1",9,"11,9",2,"3,6","2,3",...,"1,8","2,9","8,5","4,7","5,5","1,8","0,9","8,9","1,9","5,8"
4,2015,"11,7","14,3","11,7","11,5",11,"12,1","2,4","4,6","2,1",...,"2,2",3,"8,3","4,7","4,5","1,6","1,1",9,2,"6,6"
5,2016,"15,9","15,2","14,6","11,1","12,9","14,1","1,9",5,"3,7",...,"2,3","3,6","9,8","5,9","6,1","2,2","1,8","12,3","2,6","7,5"

In [234]:
#Renomeando a vari치vel C칩digo para time
international_poverty_states_br_T.rename(columns = {'C칩digo' : 'time'}, inplace = True)
print(international_poverty_states_br_T)

    time    12    27    13    16    29    23   53   32   52  ...   41   33  \
1   2012  14,3  13,1  12,6   8,2  14,5  14,5  2,1  3,2  2,1  ...  2,3  3,5
2   2013  13,1  14,2  11,2   5,6    12  13,8  2,8  3,7  1,8  ...  1,7  3,3
3   2014  11,1  13,8  10,1   7,1     9  11,9    2  3,6  2,3  ...  1,8  2,9
4   2015  11,7  14,3  11,7  11,5    11  12,1  2,4  4,6  2,1  ...  2,2    3
5   2016  15,9  15,2  14,6  11,1  12,9  14,1  1,9    5  3,7  ...  2,3  3,6
6   2017  16,8  16,9  15,1    10  15,6  13,9  3,7  5,6  3,2  ...    3  4,1
7   2018  16,3  19,3  15,5  10,7  15,3  13,6  3,3  4,5  3,4  ...  3,1  4,2
8   2019  17,8  16,5  16,8   7,9  14,5  13,5  1,8  3,9  3,7  ...  2,8  4,5
9   2020  10,4  12,2  13,2  10,5  10,3   9,9  2,9  4,4  3,3  ...  3,9  5,8
10  2021  17,6  16,4  16,2  11,8    17    16  4,3  7,2  3,8  ...  3,9  7,6
11  2022    14  13,1  10,5   7,9  11,9  10,9  1,8  4,1  2,7  ...  2,9  4,5

      24   11    14   43   42    28   35   17
1   10,3  6,1   6,5  2,2  1,5  11,9  2,2  6,5
2    8,7    6   5,6  1,7  1,1   9,9    2  7,4
3    8,5  4,7   5,5  1,8  0,9   8,9  1,9  5,8
4    8,3  4,7   4,5  1,6  1,1     9    2  6,6
5    9,8  5,9   6,1  2,2  1,8  12,3  2,6  7,5
6     12  5,3   7,9  2,7  1,6    15    3  5,8
7   11,6  5,3   9,4  2,4  1,6  15,4  3,1    8
8     12  5,2  12,5  2,5  1,7    14  2,7  8,9
9    6,3  5,2  10,4  2,5    2   8,4  3,3  5,9
10  14,9  8,1  11,3  2,9  2,4  14,9  4,4  7,6
11   9,4  4,3   7,8  2,5  1,8   8,9  2,9  4,9

[11 rows x 28 columns]

In [235]:
#Salvando nosso DF
international_poverty_states_br = international_poverty_states_br_T
international_poverty_states_br.to_csv('/content/drive/MyDrive/Bases de Dados para Indicadores EUROFOUND/Bases Finais/international_poverty_states_br.csv',encoding='UTF-8', index = False)